---
version: '3.9'
services:
  chatbot:
    container_name: chatbot
    image: gcr.io/${GCP_PROJECT:-local}/chatbot:${IMAGE_TAG:-latest}
    working_dir: /mnt/project/app
    build:
      context: ..
      dockerfile: ./app/Dockerfile
    restart: always
    ports:
    - 8080:8080
    volumes:
    - ..:/mnt/project
    - $HOME/.config/gcloud:/root/.config/gcloud
    env_file:
    - ../.env
